
import Head from 'next/head';
import { Header, Footer, About } from '../components';

function about() {
    return (
        <>
            <Head>
                <title>About page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <About />
            <Footer />
        </>
    )
}

export default about
