import Head from 'next/head';
import styled from 'styled-components';
import { Header, Footer, About } from '../components';

const StyledAbout = styled.main`
    padding: 32px 0;
`;
function about() {
    return (
        <>
            <Head>
                <title>About page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <StyledAbout>
                <About />
            </StyledAbout>
            <Footer />
        </>
    );
}

export default about;
