
import Head from 'next/head';
import { Header, Footer, Experience } from '../components';

function about() {
    return (
        <div>
            <Head>
                <title>Home page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Experience />
            <Footer />
        </div>
    )
}

export default about
