
import Head from 'next/head';
import { Header, Footer} from '../components';

function Projects() {
    return (
        <>
            <Head>
                <title>Project page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <p>projects</p>
            <Footer />
        </>
    )
}

export default Projects