import Head from 'next/head';
import styled from 'styled-components';
import { AppContainer } from '../src/assets/styles/elements';
import { Header, Footer, Projects, PageTitle, ProjectsFilter } from '../src/components';
import projectsList from '../src/assets/json/projects.json';

const StyledProjects = styled.main`
    padding: 32px 0;
`;

function ProjectsPage() {
    return (
        <>
            <Head>
                <title>Project page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <StyledProjects>
                <AppContainer>
                    <PageTitle title="Projects." />
                    <ProjectsFilter />
                    <Projects projects={projectsList} GridColumns={3} />
                </AppContainer>
            </StyledProjects>
            <Footer />
        </>
    );
}

export default ProjectsPage;
